# Generated by Django 6.0.2 on 2026-02-25 21:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Имя пользователя должно содержать только латиницу и цифры.",
                                regex="^[a-zA-Z0-9]+$",
                            )
                        ],
                        verbose_name="Имя",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "home_page",
                    models.URLField(
                        blank=True, null=True, verbose_name="Главная страница"
                    ),
                ),
                ("text", models.TextField(verbose_name="Ваш комментарий")),
                (
                    "mediafile",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="attachments/%Y/%m/%d/",
                        verbose_name="Прикреплённый файл",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="comments.comment",
                        verbose_name="Основной комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ["-created_at"],
            },
        ),
    ]
